name: API test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.4.0
        with:
          chrome-version: latest

      - name: Build with Gradle
        working-directory: api-test
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Run Tests
        working-directory: api-test
        run: ./gradlew clean test

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-cucumber-html-report
          path: api-test/build/cucumber-html-reports

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-test-report
          path: api-test/build/reports/tests/test
