name: API test

on:
  push:
    paths:
      - "api-test/**"
  pull_request:
    paths:
      - "api-test/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Checkout the repository

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Chrome with extra capabilities
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
          # chrome-options: '--headless'

      - name: Build with Gradle
        working-directory: api-test
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Run Tests
        working-directory: api-test
        run: ./gradlew clean test
